version: '3.9'

services:
  elementum:
    build:
      context: .
      dockerfile: Dockerfile
    image: elementum:latest
    container_name: elementum_web
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
